spring:
    security:
      oauth2:
        authorizationserver:
            client:
              java-talks:
                  registration:
                      client-id: "javatalks-web-app"
                      client-secret: "{noop}secret"
                      client-authentication-methods:
                        - "client_secret_basic"
                      authorization-grant-types:
                        - "authorization_code"
                        - "refresh_token"
                        - "client_credentials"
                      redirect-uris:
                        - "http://127.0.0.1:8080/login/oauth2/code/java-talks"
                      scopes:
                        - "openid"
                        - "profile"
                        - "email"
                  require-authorization-consent: true
      user:
          name: "sharifyy"
          password: "{noop}secret"
server:
    port: 8081
logging:
    level:
        org:
            springframework:
                security: trace
