server:
    port: 8081
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
    sql:
        init:
            schema-locations:
                - 'classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql'

jwt:
    key:
        id: 'customize-id-0354-4b33-867f-23d7b5e56cc5'
        public: classpath:certs/public.pem
        private: classpath:certs/private.pem
logging:
    level:
        org:
            springframework:
                security: trace
